name: restaurants-prod-cd

on:
  push:
    branches: 
    - main
  workflow_dispatch:


jobs:
  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.1
        with:
          dotnet-version: 8.0.108

      - name: Restore Dependencies
        run: dotnet restore src/src.sln

      - name: Build the API
        run: dotnet build src/src.sln --no-restore -c Release

      - name: Publish Locally
        run: dotnet publish src/Restaurants.API --output ${{env.DOTNET_ROOT}}/publish --no-build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: publish-artifact
          path: ${{env.DOTNET_ROOT}}/publish

  deploy-dev:
    environment: 
      name: "Development"
      url: ${{ steps.dev-deployment.outputs.webapp-url }}
    runs-on: ubuntu-24.04
    needs: build-and-test
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: publish-artifact

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.1
        id: dev-deployment
        # This step automatically finds the package to deploy (which is publish-artifact in this case) so no need to specify a "package" property.
        with:
          app-name: app-restaurants-italynorth-001
          publish-profile: ${{ secrets.DEV_PUBLISH_PROFILE }}

  deploy-prod: 
    environment:
      name: "Production"
      url: ${{ steps.prod-deployment.outputs.webapp-url }}
    runs-on: ubuntu-24.04
    needs: deploy-dev
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        id: prod-deployment
        with:
          name: publish-artifact

      - name: Azure WebApp
        uses: Azure/webapps-deploy@v3.0.1
        # This step automatically finds the package to deploy (which is publish-artifact in this case) so no need to specify a "package" property.
        with:
          app-name: app-restaurants-italynorth-prod
          publish-profile: ${{ secrets.PROD_PUBLISH_PROFILE }}
